/*자동차별 평균 대여기간을 구하는 SQL*/
SELECT A.CAR_ID
     , TO_CHAR(ROUND(AVG((A.END_DATE - A.START_DATE) + 1),1), 'FM999.0') AS AVERAGE_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 WHERE 1=1
 GROUP
    BY A.CAR_ID
HAVING ROUND(AVG((A.END_DATE - A.START_DATE) + 1),1) >= 7
 ORDER
    BY ROUND(AVG((A.END_DATE - A.START_DATE) + 1),1) DESC
     , A.CAR_ID DESC